---
deployment:
  tasks:
    # Install dependencies
    - export DEPLOYPATH=/home/$USER/public_html
    - cd $DEPLOYPATH
    - npm ci --production
    
    # Build the application
    - npm run build
    
    # Copy built files to web root
    - cp -R dist/* $DEPLOYPATH/
    
    # Set proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    
    # Ensure .git directory is not publicly accessible
    - echo "deny from all" > $DEPLOYPATH/.git/.htaccess
    
    # Create .htaccess for SPA routing
    - |
      cat > $DEPLOYPATH/.htaccess << 'EOF'
      RewriteEngine On
      RewriteBase /
      
      # Handle Angular and React Router
      RewriteRule ^index\.html$ - [L]
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule . /index.html [L]
      
      # Security headers
      Header always set X-Content-Type-Options nosniff
      Header always set X-Frame-Options DENY
      Header always set X-XSS-Protection "1; mode=block"
      Header always set Referrer-Policy "strict-origin-when-cross-origin"
      
      # Cache static assets
      <FilesMatch "\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$">
        ExpiresActive On
        ExpiresDefault "access plus 1 year"
      </FilesMatch>
      
      # Deny access to sensitive files
      <FilesMatch "\.(env|log|json)$">
        Order allow,deny
        Deny from all
      </FilesMatch>
      
      # Deny access to .git directory
      RedirectMatch 404 /\.git
      EOF
